[ip]
name    = "hamming"
version = "1.0.1"
library = "ecc"
summary = "Hamming-code SECDED implementation."
keywords = ["ecc", "code"]

# To learn more about writing the manifest, see https://c-rus.github.io/orbit/reference/manifest.html
[dependencies]

[dev-dependencies]
testkit = "1.0.3"