[ip]
name    = "hamming"
version = "1.0.0"
library = "ecc"
summary = "Hamming-code SECDED implementation."
keywords = ["ecc", "code"]

# To learn more about writing the manifest, see https://c-rus.github.io/orbit/4_topic/2_orbittoml.html

[dev-dependencies]
toolbox = "1.0.0"