[ip]
name    = "hamming"
library = "ecc"
version = "0.1.0"
summary = "Hamming-code SECDED implementation."

# To learn more about writing the manifest, see https://c-rus.github.io/orbit/4_topic/2_orbittoml.html

[dependencies]
toolbox = "1.0.0"